AWSTemplateFormatVersion: '2010-09-09'
Description: IaC Practice 
Resources:
  EC2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      SecurityGroupIds: 
        - 'sg-0a9c371825823cffb'
     # SubnetId: 'subnet-02f0fdefd08e4aa7b'
      # Change this, as applicable to you      
      KeyName: aws-test-key
      # Change this, as applicable to you
      # You may need to find out what instance types are available in your region - use https://cloud-images.ubuntu.com/locator/ec2/
      ImageId: 'ami-08d4ac5b634553e16' 
      InstanceType: t3.micro
 
